//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treeview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string Title { get; set; }
        public string BodyMsg { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Vote { get; set; }
        public string DateTime { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
