//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treeview
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSite
    {
        public int ID { get; set; }
        public string Link { get; set; }
        public string IP { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string countrycode { get; set; }
        public string countryname { get; set; }
        public string city { get; set; }
        public string regioncode { get; set; }
        public string regionname { get; set; }
        public string areacode { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string zipcode { get; set; }
        public string IPDesc { get; set; }
    }
}
