//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treeview
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CosmicVerseEntities : DbContext
    {
        public CosmicVerseEntities()
            : base("name=CosmicVerseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Article> Articles { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Content> Contents { get; set; }
        public DbSet<LinkHit> LinkHits { get; set; }
        public DbSet<LinkSite> LinkSites { get; set; }
        public DbSet<MainSection> MainSections { get; set; }
        public DbSet<Personal> Personals { get; set; }
        public DbSet<SubSection> SubSections { get; set; }
        public DbSet<tbl_Conversation> tbl_Conversation { get; set; }
        public DbSet<tbl_Dep> tbl_Dep { get; set; }
        public DbSet<tbl_Product> tbl_Product { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
    }
}
