//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treeview
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int ProductID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ChildID { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> Hint { get; set; }
        public Nullable<decimal> UnitinStock { get; set; }
        public Nullable<decimal> Discontinued { get; set; }
    }
}
